language: smalltalk
sudo: false

os:
  - linux
#  - osx
services: 
  - mongodb
smalltalk:
  - Pharo-5.0
#  - Pharo-4.0
#  - Pharo-3.0

# Target mongodb v3.0 as lowest version
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
